# This is a basic workflow to help you get started with Actions

name: Test Debug

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    name: Test Debug Variant
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # - name: Make Gradle Executable
      #   run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Execute Gradle Command - testDebugUnitTest
        run: ./gradlew testDebugUnitTest